services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MoolyFTW12.
      MYSQL_DATABASE: argus_clone
      MYSQL_USER: nacho_verde
      MYSQL_PASSWORD: MoolyFTW12.
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - db-data:/var/log/mysql

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:8.4.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-data:
  rabbitmq_data:
  redis_data: