spring.application.name=argus-clone
server.port=8080

spring.threads.virtual.enabled=true

spring.datasource.url=${AIVEN_DATASOURCE_URL}
spring.datasource.username=${AIVEN_USERNAME}
spring.datasource.password=${AIVEN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET_STRING}

admin.secret=${ADMIN_SECRET}

spring.cache.type=caffeine
spring.cache.cache-names=course-cache,course-ids-cache,instructor-courses-cache,instructor-ids-cache,student-courses-cache,group-cache,course-groups-cache,group-students-cache,student-group-ids-cache,student-course-ids-cache,instructor-cache,group-lectures-cache,user-details-cache,student-course-scores-cache,student-cache,student-course-results-cache,syllabus-cache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterAccess=10m