spring.application.name=argus-clone

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/argus_clone
spring.datasource.username=root
spring.datasource.password=MoolyFTW12.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect